require("core.globals")
require("core.options")
require("core.keymaps")
require("core.autocommands")
require("core.commands")

require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.toggleterm")
require("user.project")
require("user.impatient")
require("user.illuminate")
require("user.indentline")
require("user.alpha")
require("user.lsp")
require("user.dap")

require("user.vim-surround")
require("user.whichkey")
require("user.spectre")
require("user.crates")
require("user.minimap")
require("user.diffview")
require("user.dressing")
require("user.wilder")

require("user.lualine")
